/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tms.views;

import SeverConnector.Connector;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tms.controllercommon.AttendenceController;
import tms.controllercommon.ClassController;
import tms.controllercommon.RegistrationController;
import tms.controllercommon.StudentController;
import tms.model.Attendence;
import tms.model.ClassS;
import tms.model.Student;

/**
 *
 * @author Nuwantha
 */
public class AttendenceManagement extends javax.swing.JDialog {

    RegistrationController registrationController;
    ClassController classController;
    StudentController studentController;
    AttendenceController attendenceController;

    /**
     * Creates new form AttendenceManagement
     */
    public AttendenceManagement(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {

            Connector sConnector = Connector.getSConnector();
            registrationController = sConnector.getRegistrationController();
            classController = sConnector.getClassController();
            studentController = sConnector.getStudentController();
            attendenceController = sConnector.getAttendenceController();
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | InterruptedException | ClassNotFoundException ex) {
            Logger.getLogger(AttendenceManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadClassIdCombo(classIdComboA);
        loadClassIdCombo(classIdComboE);
        dateValidation.setVisible(false);
    }

    
    public AttendenceManagement(java.awt.Frame parent, boolean modal,int a) {
        this(parent, modal);
        jTabbedPane1.setSelectedIndex(a);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        classIdAddMarkL = new javax.swing.JLabel();
        classIdComboA = new javax.swing.JComboBox<>();
        loadButtonA = new javax.swing.JButton();
        datelabelA = new javax.swing.JLabel();
        dateChoosserA = new com.toedter.calendar.JDateChooser();
        dateValidation = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendenceTable = new javax.swing.JTable();
        markAttendenceB = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        classIdAddMarkL1 = new javax.swing.JLabel();
        classIdComboE = new javax.swing.JComboBox<>();
        loadButtonE = new javax.swing.JButton();
        datelabelA1 = new javax.swing.JLabel();
        dateChoosserE = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        attendenceTableE = new javax.swing.JTable();
        editAttendenceB = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        classIdAddMarkL2 = new javax.swing.JLabel();
        searchByCombo = new javax.swing.JComboBox<>();
        loadButtonE1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        desktopPaneAtendence = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classIdAddMarkL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classIdAddMarkL.setText("Class Id");

        classIdComboA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classIdComboAActionPerformed(evt);
            }
        });

        loadButtonA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        loadButtonA.setText("Load");
        loadButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonAActionPerformed(evt);
            }
        });

        datelabelA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        datelabelA.setText("Date");

        dateValidation.setBackground(new java.awt.Color(255, 0, 0));
        dateValidation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dateValidation.setForeground(new java.awt.Color(255, 0, 0));
        dateValidation.setText("invalid date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classIdAddMarkL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datelabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dateChoosserA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(loadButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)))
                            .addComponent(classIdComboA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classIdAddMarkL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(classIdComboA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(datelabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateChoosserA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(loadButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        attendenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student Id", "Attendence"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(attendenceTable);
        if (attendenceTable.getColumnModel().getColumnCount() > 0) {
            attendenceTable.getColumnModel().getColumn(0).setResizable(false);
            attendenceTable.getColumnModel().getColumn(1).setResizable(false);
            attendenceTable.getColumnModel().getColumn(2).setResizable(false);
        }

        markAttendenceB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        markAttendenceB.setText(" Mark Attendence");
        markAttendenceB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAttendenceBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(markAttendenceB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(markAttendenceB)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mark Attendence", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classIdAddMarkL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classIdAddMarkL1.setText("Class Id");

        classIdComboE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classIdComboEActionPerformed(evt);
            }
        });

        loadButtonE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        loadButtonE.setText("Load");
        loadButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonEActionPerformed(evt);
            }
        });

        datelabelA1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        datelabelA1.setText("Date");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateChoosserE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(loadButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classIdAddMarkL1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datelabelA1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(classIdComboE, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classIdAddMarkL1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(classIdComboE, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(datelabelA1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateChoosserE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(loadButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        attendenceTableE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student Id", "Attendence"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(attendenceTableE);

        editAttendenceB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        editAttendenceB.setText(" Edit Attendence");
        editAttendenceB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAttendenceBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editAttendenceB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(editAttendenceB)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edit Attendence", jPanel4);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classIdAddMarkL2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classIdAddMarkL2.setText("Search By ");

        searchByCombo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        searchByCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class", "Student", " " }));
        searchByCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByComboActionPerformed(evt);
            }
        });

        loadButtonE1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        loadButtonE1.setText("Load");
        loadButtonE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonE1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(classIdAddMarkL2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loadButtonE1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(searchByCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classIdAddMarkL2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(searchByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(loadButtonE1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        desktopPaneAtendence.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout desktopPaneAtendenceLayout = new javax.swing.GroupLayout(desktopPaneAtendence);
        desktopPaneAtendence.setLayout(desktopPaneAtendenceLayout);
        desktopPaneAtendenceLayout.setHorizontalGroup(
            desktopPaneAtendenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        desktopPaneAtendenceLayout.setVerticalGroup(
            desktopPaneAtendenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneAtendence)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneAtendence)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("View Attendence", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classIdComboAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classIdComboAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classIdComboAActionPerformed

    private void loadButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonAActionPerformed
        try {
            String classId = String.valueOf(classIdComboA.getSelectedItem());
            ArrayList<Student> students = registrationController.getStudentOfClass(classId);
            DefaultTableModel tableModel = (DefaultTableModel) attendenceTable.getModel();
            tableModel.getDataVector().removeAllElements();
            revalidate();
            for (Student student : students) {
                tableModel.addRow(new Object[]{student.getName(), student.getStudentId(), null});
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StudentMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadButtonAActionPerformed

    private void markAttendenceBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAttendenceBActionPerformed
        dateValidation.setVisible(false);
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date dateD = dateChoosserA.getDate();
        String date = df.format(dateD);

        int conductedYear = Integer.parseInt(date.substring(0, 4));
        int conductedMonth = Integer.parseInt(date.substring(5, 7));
        int conductedDay = Integer.parseInt(date.substring(8, 10));
        Calendar now = Calendar.getInstance();
        int currentYear = now.get(Calendar.YEAR);
        int currentMonth = now.get(Calendar.MONTH) + 1;
        int currentDay = now.get(Calendar.DAY_OF_MONTH);
        System.out.println(conductedMonth + "  " + conductedDay + "  " + currentMonth + " " + currentDay);
        if (conductedYear > currentYear || (conductedYear == currentYear && conductedMonth > currentMonth) || (conductedYear == currentYear && conductedMonth == currentMonth && conductedDay > currentDay)) {
            dateValidation.setVisible(true);
        } else {
            try {
                ArrayList<Attendence> attendences = new ArrayList<Attendence>();

                DefaultTableModel model = (DefaultTableModel) attendenceTable.getModel();
                boolean nextStep = true;
                for (int count = 0; count < model.getRowCount(); count++) {

                    String studentId = model.getValueAt(count, 1).toString();
                    Student student = studentController.searchStudent(studentId);
                    int status = Integer.parseInt(model.getValueAt(count, 2).toString());
                    if (!(status == 1 || status == 0)) {
                        nextStep = false;
                        continue;
                    }
                    String classId = String.valueOf(classIdComboA.getSelectedItem());

                    Attendence attendence = new Attendence(classId, studentId, date, status);
                    attendences.add(attendence);

                }
                if (nextStep) {
                    boolean addNewAttendence = attendenceController.addNewAttendence(attendences);
                    if (addNewAttendence) {
                        JOptionPane.showMessageDialog(this, "attendence is added successfully");

                    } else {
                        JOptionPane.showMessageDialog(this, "attendence is not added successfully");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Enter 1 or 2 for attendence");

                }
            } catch (RemoteException | ClassNotFoundException ex) {
                Logger.getLogger(StudentMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());

            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(this, "Enter 1 or 2 for attendence");
            }
        }
    }//GEN-LAST:event_markAttendenceBActionPerformed

    private void classIdComboEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classIdComboEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classIdComboEActionPerformed

    private void loadButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonEActionPerformed

        try {
            String classId = String.valueOf(classIdComboA.getSelectedItem());
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date dateD = dateChoosserE.getDate();
            String date = df.format(dateD);

            ArrayList<Attendence> searchAttendence = attendenceController.searchClassAttendence(classId, date);
            DefaultTableModel tableModel = (DefaultTableModel) attendenceTableE.getModel();
            tableModel.getDataVector().removeAllElements();
            revalidate();
            for (Attendence attendence : searchAttendence) {
                Student student = studentController.searchStudent(attendence.getStudentId());
                tableModel.addRow(new Object[]{student.getName(), student.getStudentId(), attendence.getStatus()});
            }
        } catch (RemoteException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AttendenceManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_loadButtonEActionPerformed

    private void editAttendenceBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAttendenceBActionPerformed

        try {
            ArrayList<Attendence> attendences = new ArrayList<Attendence>();

            DefaultTableModel model = (DefaultTableModel) attendenceTableE.getModel();

            for (int count = 0; count < model.getRowCount(); count++) {

                String studentId = model.getValueAt(count, 1).toString();
                int status = Integer.parseInt(model.getValueAt(count, 2).toString());
                String classId = String.valueOf(classIdComboE.getSelectedItem());
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                Date dateD = dateChoosserE.getDate();
                String date = df.format(dateD);

                Attendence attendence = new Attendence(classId, studentId, date, status);
                attendences.add(attendence);
            }

            boolean editAttendence = attendenceController.editAttendence(attendences);
            if (editAttendence) {
                JOptionPane.showMessageDialog(this, "attendence is updated successfully");
                
            } else {
                JOptionPane.showMessageDialog(this, "attendence is not updated successfully");
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StudentMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_editAttendenceBActionPerformed

    private void searchByComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByComboActionPerformed

    private void loadButtonE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonE1ActionPerformed
        int selectedIndex = searchByCombo.getSelectedIndex();
        if (selectedIndex == 0) {
            AttendenceViewByClass attendenceViewByClass = new AttendenceViewByClass();
            attendenceViewByClass.setSize(desktopPaneAtendence.getSize());
            desktopPaneAtendence.removeAll();
            desktopPaneAtendence.add(attendenceViewByClass);
            attendenceViewByClass.setVisible(true);
            attendenceViewByClass.requestFocus();
        } else {
            AttendenceViewByStudent attendenceViewByStudent = new AttendenceViewByStudent();
            attendenceViewByStudent.setSize(desktopPaneAtendence.getSize());
            desktopPaneAtendence.removeAll();
            desktopPaneAtendence.add(attendenceViewByStudent);
            attendenceViewByStudent.setVisible(true);
            attendenceViewByStudent.requestFocus();

        }


    }//GEN-LAST:event_loadButtonE1ActionPerformed

    private void loadClassIdCombo(JComboBox comboBox) {
        comboBox.removeAllItems();
        try {
            ArrayList<ClassS> allClass = classController.getAllClassForNewYear();
            for (ClassS cls : allClass) {
                comboBox.addItem(cls.getClassId());
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StudentMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendenceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendenceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendenceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendenceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AttendenceManagement dialog = new AttendenceManagement(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attendenceTable;
    private javax.swing.JTable attendenceTableE;
    private javax.swing.JLabel classIdAddMarkL;
    private javax.swing.JLabel classIdAddMarkL1;
    private javax.swing.JLabel classIdAddMarkL2;
    private javax.swing.JComboBox<String> classIdComboA;
    private javax.swing.JComboBox<String> classIdComboE;
    private com.toedter.calendar.JDateChooser dateChoosserA;
    private com.toedter.calendar.JDateChooser dateChoosserE;
    private javax.swing.JLabel dateValidation;
    private javax.swing.JLabel datelabelA;
    private javax.swing.JLabel datelabelA1;
    private javax.swing.JDesktopPane desktopPaneAtendence;
    private javax.swing.JButton editAttendenceB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loadButtonA;
    private javax.swing.JButton loadButtonE;
    private javax.swing.JButton loadButtonE1;
    private javax.swing.JButton markAttendenceB;
    private javax.swing.JComboBox<String> searchByCombo;
    // End of variables declaration//GEN-END:variables
}
