/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tms.views;

import SeverConnector.Connector;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tms.controllercommon.ClassController;
import tms.model.ClassS;
import tms.model.Student;

/**
 *
 * @author Nuwantha
 */
public class ClassDetail extends javax.swing.JDialog {

    ClassController classController;

    /**
     * Creates new form NewJDialog
     */

    public ClassDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            classController = Connector.getSConnector().getClassController();
        } catch (SQLException | ClassNotFoundException | NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(ClassDetail.class.getName()).log(Level.SEVERE, null, ex);
        }

        setClassDetailID();
        loadClassCombo();

    }

    public ClassDetail(java.awt.Frame parent, boolean modal,int a) {
        this(parent, modal);
        jTabbedPane1.setSelectedIndex(a);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        addClassDetailPanel = new javax.swing.JPanel();
        classIdLA = new javax.swing.JLabel();
        gradeLA = new javax.swing.JLabel();
        yearLA = new javax.swing.JLabel();
        conductedDateLA = new javax.swing.JLabel();
        amountLA = new javax.swing.JLabel();
        amountTA = new javax.swing.JTextField();
        addB = new javax.swing.JButton();
        classIdT = new javax.swing.JTextField();
        gradeCA = new javax.swing.JComboBox<>();
        yearCA = new javax.swing.JComboBox<>();
        dateCA = new javax.swing.JComboBox<>();
        editClassDetialPanel = new javax.swing.JPanel();
        classIdLE = new javax.swing.JLabel();
        gradeLE = new javax.swing.JLabel();
        yearLE = new javax.swing.JLabel();
        dateLE = new javax.swing.JLabel();
        amountLE = new javax.swing.JLabel();
        amountTE = new javax.swing.JTextField();
        editB = new javax.swing.JButton();
        gradeCE = new javax.swing.JComboBox<>();
        yearCE = new javax.swing.JComboBox<>();
        dateCE = new javax.swing.JComboBox<>();
        classIdC = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N

        addClassDetailPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classIdLA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classIdLA.setText("ClassId");

        gradeLA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        gradeLA.setText("Grade");

        yearLA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        yearLA.setText("Year");

        conductedDateLA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        conductedDateLA.setText("Conducted Date");

        amountLA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        amountLA.setText("ClassFeesAmount");

        amountTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTAActionPerformed(evt);
            }
        });

        addB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        addB.setText("Add New Class");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        classIdT.setEditable(false);
        classIdT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classIdTActionPerformed(evt);
            }
        });

        gradeCA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gradeCA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grade 3", "grade 4", "grade 5", " " }));

        yearCA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", " " }));

        dateCA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateCA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sunday", "Monday", "Tuesday", "Wednsday", "Thursday", "Friday", "Saturday", " " }));

        javax.swing.GroupLayout addClassDetailPanelLayout = new javax.swing.GroupLayout(addClassDetailPanel);
        addClassDetailPanel.setLayout(addClassDetailPanelLayout);
        addClassDetailPanelLayout.setHorizontalGroup(
            addClassDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addClassDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addClassDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classIdLA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gradeLA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearLA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conductedDateLA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountLA, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(addClassDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addB, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(amountTA)
                    .addComponent(classIdT)
                    .addComponent(gradeCA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearCA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateCA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        addClassDetailPanelLayout.setVerticalGroup(
            addClassDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addClassDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addClassDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(classIdLA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classIdT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addClassDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gradeLA, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(gradeCA))
                .addGap(18, 18, 18)
                .addGroup(addClassDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addClassDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conductedDateLA, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(dateCA))
                .addGap(18, 18, 18)
                .addGroup(addClassDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Class Detail", addClassDetailPanel);

        editClassDetialPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classIdLE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classIdLE.setText("ClassId");

        gradeLE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        gradeLE.setText("Grade");

        yearLE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        yearLE.setText("Year");

        dateLE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        dateLE.setText("Conducted Date");

        amountLE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        amountLE.setText("ClassFeesAmount");

        amountTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTEActionPerformed(evt);
            }
        });

        editB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        editB.setText("Edit New Class");
        editB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBActionPerformed(evt);
            }
        });

        gradeCE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gradeCE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grade 3", "grade 4", "grade 5", " " }));

        yearCE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", " " }));

        dateCE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateCE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sunday", "Monday", "Tuesday", "Wednsday", "Thursday", "Friday", "Saturday", " " }));

        classIdC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classIdC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                classIdCItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout editClassDetialPanelLayout = new javax.swing.GroupLayout(editClassDetialPanel);
        editClassDetialPanel.setLayout(editClassDetialPanelLayout);
        editClassDetialPanelLayout.setHorizontalGroup(
            editClassDetialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editClassDetialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editClassDetialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classIdLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gradeLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountLE, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(editClassDetialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editB, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(amountTE)
                    .addComponent(gradeCE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearCE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateCE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classIdC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        editClassDetialPanelLayout.setVerticalGroup(
            editClassDetialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editClassDetialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editClassDetialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(classIdLE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classIdC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editClassDetialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gradeLE, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(gradeCE))
                .addGap(18, 18, 18)
                .addGroup(editClassDetialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editClassDetialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateLE, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(dateCE))
                .addGap(18, 18, 18)
                .addGroup(editClassDetialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(editB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Class Detail", editClassDetialPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Add Student");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classIdTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classIdTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classIdTActionPerformed

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed

        String classId = classIdT.getText();
        int grade = gradeCA.getSelectedIndex() + 3;
        int year = Integer.parseInt(String.valueOf(yearCA.getSelectedItem()));
        String date = String.valueOf(dateCA.getSelectedItem());
        int amount = Integer.parseInt(amountTA.getText());
        ClassS classS = new ClassS(classId, grade, date, amount, year);
        try {
            boolean addNewClass = classController.addNewClass(classS);
            if (addNewClass) {
                JOptionPane.showMessageDialog(this, "class is added succesfully");
                setClassDetailID();
                amountTA.setText("");
                loadClassCombo();

            } else {
                JOptionPane.showMessageDialog(this, "class is not added successfully");
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClassDetail.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addBActionPerformed

    private void amountTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTAActionPerformed

    private void amountTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTEActionPerformed

    private void editBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBActionPerformed

        String classId = String.valueOf(classIdC.getSelectedItem());
        int grade = gradeCE.getSelectedIndex() + 3;
        int year = Integer.parseInt(String.valueOf(yearCE.getSelectedItem()));
        String date = String.valueOf(dateCE.getSelectedItem());
        int amount = Integer.parseInt(amountTE.getText());
        ClassS classS = new ClassS(classId, grade, date, amount, year);
        try {
            boolean editClassDetail = classController.editClassDetail(classS);
            if (editClassDetail) {
                JOptionPane.showMessageDialog(this, "class is updated succesfully");
                
            } else {
                JOptionPane.showMessageDialog(this, "class is not updated successfully");
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClassDetail.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_editBActionPerformed

    private void classIdCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_classIdCItemStateChanged
        try {
            String classid = String.valueOf(classIdC.getSelectedItem());
            ClassS searchClass = classController.searchClass(classid);
            amountTE.setText(String.valueOf(searchClass.getClassFeesAmount()));
            yearCE.setSelectedItem(String.valueOf(searchClass.getYear()));
            gradeCE.setSelectedIndex(searchClass.getGrade()-3);
            dateCE.setSelectedItem(searchClass.getConductedDate());
// TODO add your handling code here:
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClassDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_classIdCItemStateChanged

    private void setClassDetailID() {
        try {
            int classCount = classController.getClassCount() + 1;
            if (classCount < 10) {
                classIdT.setText("CL00" + String.valueOf(classCount));
            } else if (classCount < 100) {
                classIdT.setText("CL0" + String.valueOf(classCount));
            } else {
                classIdT.setText("CL" + String.valueOf(classCount));
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClassDetail.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadClassCombo() {
        classIdC.removeAllItems();
        try {
            ArrayList<ClassS> allClass = classController.getAllClass();
            for (ClassS cls : allClass) {
                classIdC.addItem(cls.getClassId());
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StudentMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClassDetail dialog = new ClassDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JPanel addClassDetailPanel;
    private javax.swing.JLabel amountLA;
    private javax.swing.JLabel amountLE;
    private javax.swing.JTextField amountTA;
    private javax.swing.JTextField amountTE;
    private javax.swing.JComboBox<String> classIdC;
    private javax.swing.JLabel classIdLA;
    private javax.swing.JLabel classIdLE;
    private javax.swing.JTextField classIdT;
    private javax.swing.JLabel conductedDateLA;
    private javax.swing.JComboBox<String> dateCA;
    private javax.swing.JComboBox<String> dateCE;
    private javax.swing.JLabel dateLE;
    private javax.swing.JButton editB;
    private javax.swing.JPanel editClassDetialPanel;
    private javax.swing.JComboBox<String> gradeCA;
    private javax.swing.JComboBox<String> gradeCE;
    private javax.swing.JLabel gradeLA;
    private javax.swing.JLabel gradeLE;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> yearCA;
    private javax.swing.JComboBox<String> yearCE;
    private javax.swing.JLabel yearLA;
    private javax.swing.JLabel yearLE;
    // End of variables declaration//GEN-END:variables
}
