/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tms.views;

import SeverConnector.Connector;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tms.common_classes.MSGHandler;
import tms.controllercommon.ClassController;
import tms.controllercommon.ClassFeesController;
import tms.controllercommon.RegistrationController;
import tms.controllercommon.StudentController;
import tms.model.ClassFees;
import tms.model.ClassS;
import tms.model.Student;

/**
 *
 * @author Nuwantha
 */
public class ClassFeesManagement extends javax.swing.JDialog {

    ClassController classController;
    RegistrationController registrationController;
    StudentController studentController;
    ClassFeesController classFeesController;
    ArrayList<Student> students;

    /**
     * Creates new form ClassFeesId
     */
    public ClassFeesManagement(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            Connector sConnector = Connector.getSConnector();
            classController = sConnector.getClassController();
            registrationController = sConnector.getRegistrationController();
            studentController = sConnector.getStudentController();
            classFeesController = sConnector.getClassFeesController();
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException | InterruptedException ex) {
            Logger.getLogger(ClassFeesManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        loadClassIdAdd(classIdComboA);
        loadClassId(classIdComboView);
    
    
    }
    
    
    public ClassFeesManagement(java.awt.Frame parent, boolean modal,int a) {
        this(parent, modal);
        jTabbedPane1.setSelectedIndex(a);
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        classIdLabelA = new javax.swing.JLabel();
        classIdComboA = new javax.swing.JComboBox<>();
        studentIdLabelA = new javax.swing.JLabel();
        studentIdCombo = new javax.swing.JComboBox<>();
        monthLabelA = new javax.swing.JLabel();
        monthComboA = new javax.swing.JComboBox<>();
        addButtonA = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        classDeatilPanelA = new javax.swing.JPanel();
        gradeLabelA = new javax.swing.JLabel();
        gradeTextA = new javax.swing.JTextField();
        classFeesAmountLabelA = new javax.swing.JLabel();
        conductedYearLabelA = new javax.swing.JLabel();
        classFeesAmountTextA = new javax.swing.JTextField();
        conductedYearTextA = new javax.swing.JTextField();
        studentDetailPanelA = new javax.swing.JPanel();
        nameTextA = new javax.swing.JLabel();
        paprentNameTextA = new javax.swing.JLabel();
        contactNumberLabelA = new javax.swing.JLabel();
        nameTextAdd = new javax.swing.JTextField();
        paprentNameTA = new javax.swing.JTextField();
        contactNumberTextA = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        paidStudentL = new javax.swing.JLabel();
        classIdLV = new javax.swing.JLabel();
        classIdComboView = new javax.swing.JComboBox<>();
        monthLabelA1 = new javax.swing.JLabel();
        monthComboA1 = new javax.swing.JComboBox<>();
        loadB = new javax.swing.JButton();
        yesB = new javax.swing.JRadioButton();
        noB = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        classFesTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classIdLabelA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classIdLabelA.setText("Class ID");

        classIdComboA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classIdComboA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                classIdComboAItemStateChanged(evt);
            }
        });

        studentIdLabelA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        studentIdLabelA.setText("Student ID");

        studentIdCombo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        studentIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentIdComboItemStateChanged(evt);
            }
        });

        monthLabelA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        monthLabelA.setText("Month");

        monthComboA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monthComboA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "Octomber", "November", "December" }));
        monthComboA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthComboAItemStateChanged(evt);
            }
        });
        monthComboA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                monthComboAKeyReleased(evt);
            }
        });

        addButtonA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        addButtonA.setText("Add");
        addButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classIdLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIdLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthComboA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classIdComboA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIdCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(monthLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monthComboA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(classIdLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classIdComboA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentIdLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(addButtonA)
                .addGap(95, 95, 95))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classDeatilPanelA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Class Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 12))); // NOI18N

        gradeLabelA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        gradeLabelA.setText("Grade  ");

        gradeTextA.setEditable(false);
        gradeTextA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeTextAActionPerformed(evt);
            }
        });

        classFeesAmountLabelA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classFeesAmountLabelA.setText("Class Fess Amount ");

        conductedYearLabelA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        conductedYearLabelA.setText("Conducted Year ");

        classFeesAmountTextA.setEditable(false);
        classFeesAmountTextA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classFeesAmountTextAActionPerformed(evt);
            }
        });

        conductedYearTextA.setEditable(false);
        conductedYearTextA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conductedYearTextAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout classDeatilPanelALayout = new javax.swing.GroupLayout(classDeatilPanelA);
        classDeatilPanelA.setLayout(classDeatilPanelALayout);
        classDeatilPanelALayout.setHorizontalGroup(
            classDeatilPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classDeatilPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classDeatilPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(conductedYearLabelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classFeesAmountLabelA, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(gradeLabelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addGroup(classDeatilPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gradeTextA)
                    .addComponent(classFeesAmountTextA)
                    .addComponent(conductedYearTextA, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        classDeatilPanelALayout.setVerticalGroup(
            classDeatilPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classDeatilPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classDeatilPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(classDeatilPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classFeesAmountLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classFeesAmountTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(classDeatilPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conductedYearLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conductedYearTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        studentDetailPanelA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Student Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 12))); // NOI18N

        nameTextA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        nameTextA.setText("Student Name");

        paprentNameTextA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        paprentNameTextA.setText("Parent Name");

        contactNumberLabelA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberLabelA.setText("Contact Number");

        nameTextAdd.setEditable(false);

        paprentNameTA.setEditable(false);

        contactNumberTextA.setEditable(false);

        javax.swing.GroupLayout studentDetailPanelALayout = new javax.swing.GroupLayout(studentDetailPanelA);
        studentDetailPanelA.setLayout(studentDetailPanelALayout);
        studentDetailPanelALayout.setHorizontalGroup(
            studentDetailPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDetailPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentDetailPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameTextA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paprentNameTextA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactNumberLabelA, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addGroup(studentDetailPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameTextAdd)
                    .addComponent(paprentNameTA)
                    .addComponent(contactNumberTextA, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        studentDetailPanelALayout.setVerticalGroup(
            studentDetailPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDetailPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentDetailPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameTextA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentDetailPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paprentNameTextA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paprentNameTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentDetailPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumberTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classDeatilPanelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentDetailPanelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classDeatilPanelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentDetailPanelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Class Fees", jPanel1);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        paidStudentL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        paidStudentL.setText("Paid Student");

        classIdLV.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classIdLV.setText("Class Id");

        classIdComboView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classIdComboView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                classIdComboViewItemStateChanged(evt);
            }
        });

        monthLabelA1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        monthLabelA1.setText("Month");

        monthComboA1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monthComboA1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "Octomber", "November", "December" }));

        loadB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        loadB.setText("Load");
        loadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBActionPerformed(evt);
            }
        });

        buttonGroup1.add(yesB);
        yesB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        yesB.setText("Yes");

        buttonGroup1.add(noB);
        noB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        noB.setText("No");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(loadB, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classIdComboView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthComboA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paidStudentL, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classIdLV, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthLabelA1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(yesB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(noB, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paidStudentL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesB)
                    .addComponent(noB))
                .addGap(13, 13, 13)
                .addComponent(classIdLV, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classIdComboView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monthLabelA1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monthComboA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(loadB)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classFesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Student Name", "Parent", "Contact Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(classFesTable);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("Send Notification");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("View Class Fees Detail", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gradeTextAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeTextAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeTextAActionPerformed

    private void classFeesAmountTextAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classFeesAmountTextAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classFeesAmountTextAActionPerformed

    private void classIdComboAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_classIdComboAItemStateChanged

        try {

            String classId = String.valueOf(classIdComboA.getSelectedItem());
            ClassS searchClass = classController.searchClass(classId);
            gradeTextA.setText(String.valueOf(searchClass.getGrade()));
            classFeesAmountTextA.setText(String.valueOf(searchClass.getClassFeesAmount()));
            conductedYearTextA.setText(String.valueOf(searchClass.getYear()));
            nameTextAdd.setText("");
            paprentNameTA.setText("");
            contactNumberTextA.setText("");
            int month =monthComboA.getSelectedIndex()+1;
            loadStudentIdOfClass(classId,month);

        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClassFeesManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_classIdComboAItemStateChanged

    private void conductedYearTextAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conductedYearTextAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conductedYearTextAActionPerformed

    private void studentIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentIdComboItemStateChanged

        try {
            String studentId = String.valueOf(studentIdCombo.getSelectedItem());
            Student student = studentController.searchStudent(studentId);
            if (student != null) {
                nameTextAdd.setText(student.getName());
                paprentNameTA.setText(student.getParentName());
                contactNumberTextA.setText(student.getContactNumber());
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClassFeesManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentIdComboItemStateChanged

    private void addButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonAActionPerformed
        try {
            String classId = String.valueOf(classIdComboA.getSelectedItem());
            String studentId = String.valueOf(studentIdCombo.getSelectedItem());
            int month = monthComboA.getSelectedIndex() + 1;
            Student student = studentController.searchStudent(studentId);
            ClassS searchClass = classController.searchClass(classId);

            String date = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());

            System.out.println(date);
            ClassFees classFees = new ClassFees(student, searchClass, date.substring(0, 10), month);
            boolean addNewClassFees = classFeesController.addNewClassFees(classFees);
            if (addNewClassFees) {
                JOptionPane.showMessageDialog(this, "classFees is added successfully");
                loadStudentIdOfClass(classId, month);
            } else {
                JOptionPane.showMessageDialog(this, "classFees is not added successfully");

            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            //  Logger.getLogger(ClassFeesManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addButtonAActionPerformed

    private void classIdComboViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_classIdComboViewItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_classIdComboViewItemStateChanged

    private void loadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBActionPerformed
        String classId = String.valueOf(classIdComboView.getSelectedItem());
        int month = monthComboA1.getSelectedIndex()+1;
        if (yesB.isSelected()) {
            try {
                students = classFeesController.getClassFeesPaidStudents(classId, month);
            } catch (RemoteException | ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ClassFeesManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                students = classFeesController.getClassFeesNotPaidStudents(classId, month);
            } catch (RemoteException | ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ClassFeesManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        DefaultTableModel tableModel = (DefaultTableModel) classFesTable.getModel();
        tableModel.getDataVector().removeAllElements();
        
        revalidate();
        for (Student student : students) {
            tableModel.addRow(new Object[]{student.getStudentId(), student.getName(), student.getParentName(), student.getContactNumber()});
        }

    }//GEN-LAST:event_loadBActionPerformed

    private void monthComboAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthComboAKeyReleased
        String classId = String.valueOf(classIdComboA.getSelectedItem());
        int month=monthComboA.getSelectedIndex()+1;
        loadStudentIdOfClass(classId, month);
    }//GEN-LAST:event_monthComboAKeyReleased

    private void monthComboAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthComboAItemStateChanged
        String classId = String.valueOf(classIdComboA.getSelectedItem());
        int month=monthComboA.getSelectedIndex()+1;
        loadStudentIdOfClass(classId, month);
    }//GEN-LAST:event_monthComboAItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MSGHandler.sendNotification(students, "has to pay class fees for this month");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadClassId(JComboBox comboBox) {
        try {
            comboBox.removeAllItems();
            ArrayList<ClassS> allClass = classController.getAllClass();
            for (ClassS cls : allClass) {
                comboBox.addItem(cls.getClassId());
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClassFeesManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    
    private void loadClassIdAdd(JComboBox comboBox) {
        try {
            comboBox.removeAllItems();
            ArrayList<ClassS> allClass = classController.getAllClassForNewYear();
            for (ClassS cls : allClass) {
                comboBox.addItem(cls.getClassId());
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClassFeesManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadStudentIdOfClass(String classId,int month) {
        try {
            studentIdCombo.removeAllItems();
            ArrayList<Student> studentOfClass = studentController.getAvailableStudentForAddingClassFees(classId, month);
            for (Student student : studentOfClass) {
                studentIdCombo.addItem(student.getStudentId());
            }
            
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClassFeesManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassFeesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassFeesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassFeesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassFeesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClassFeesManagement dialog = new ClassFeesManagement(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButtonA;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel classDeatilPanelA;
    private javax.swing.JLabel classFeesAmountLabelA;
    private javax.swing.JTextField classFeesAmountTextA;
    private javax.swing.JTable classFesTable;
    private javax.swing.JComboBox<String> classIdComboA;
    private javax.swing.JComboBox<String> classIdComboView;
    private javax.swing.JLabel classIdLV;
    private javax.swing.JLabel classIdLabelA;
    private javax.swing.JLabel conductedYearLabelA;
    private javax.swing.JTextField conductedYearTextA;
    private javax.swing.JLabel contactNumberLabelA;
    private javax.swing.JTextField contactNumberTextA;
    private javax.swing.JLabel gradeLabelA;
    private javax.swing.JTextField gradeTextA;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton loadB;
    private javax.swing.JComboBox<String> monthComboA;
    private javax.swing.JComboBox<String> monthComboA1;
    private javax.swing.JLabel monthLabelA;
    private javax.swing.JLabel monthLabelA1;
    private javax.swing.JLabel nameTextA;
    private javax.swing.JTextField nameTextAdd;
    private javax.swing.JRadioButton noB;
    private javax.swing.JLabel paidStudentL;
    private javax.swing.JTextField paprentNameTA;
    private javax.swing.JLabel paprentNameTextA;
    private javax.swing.JPanel studentDetailPanelA;
    private javax.swing.JComboBox<String> studentIdCombo;
    private javax.swing.JLabel studentIdLabelA;
    private javax.swing.JRadioButton yesB;
    // End of variables declaration//GEN-END:variables
}
