/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tms.views;

import org.apache.batik.gvt.flow.TextLineBreaks;

/**
 *
 * @author Nuwantha
 */
public class FrontPage extends javax.swing.JFrame {

    /**
     * Creates new form FrontPage
     */
    public FrontPage() {
        initComponents();
        StudentRegistration studentRegistrationForm = new StudentRegistration(this);
        studentRegistrationForm.setSize(desktopPane.getSize());
        desktopPane.removeAll();
        desktopPane.add(studentRegistrationForm);
        studentRegistrationForm.setVisible(true);
        studentRegistrationForm.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importantButtonSet = new javax.swing.ButtonGroup();
        searchButtonSet = new javax.swing.ButtonGroup();
        applicantSearchSet = new javax.swing.ButtonGroup();
        permitSearchSet = new javax.swing.ButtonGroup();
        grantSearchSet = new javax.swing.ButtonGroup();
        landSearchSet = new javax.swing.ButtonGroup();
        searchPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        desktopJPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userLogPanel = new javax.swing.JPanel();
        userpanel = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LogOutButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        searchSetCombo = new javax.swing.JComboBox();
        goButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        internalFrameAreaPanel = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        shortcutAccessPanel = new javax.swing.JPanel();
        studentRestrationFB = new javax.swing.JButton();
        addNewStudentMarkMB = new javax.swing.JButton();
        markAtendenceFB = new javax.swing.JButton();
        addClassFeesFB = new javax.swing.JButton();
        addSchoolarshipMarksFB = new javax.swing.JButton();
        sendNotifaicationFB = new javax.swing.JButton();
        viewStudentMarksFB = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addStudentDetailM = new javax.swing.JMenuItem();
        registerStudentM = new javax.swing.JMenuItem();
        editStudentDetail = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addNewClassM = new javax.swing.JMenuItem();
        editClassDetailM = new javax.swing.JMenuItem();
        Grant = new javax.swing.JMenu();
        addNewPaperM = new javax.swing.JMenuItem();
        addPaperMarksM = new javax.swing.JMenuItem();
        viewResultM = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addAttendenceM = new javax.swing.JMenuItem();
        editAttendenceM = new javax.swing.JMenuItem();
        viewAttendenceM = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        systemMenu = new javax.swing.JMenu();
        changePasswordMenu = new javax.swing.JMenuItem();
        createNewUserMenu = new javax.swing.JMenuItem();
        viewAllUsersMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        backUpMenu = new javax.swing.JMenuItem();
        restoreMenu = new javax.swing.JMenuItem();

        searchPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Search ");

        searchButtonSet.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButton6.setText("1.Applicant");

        searchButtonSet.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButton7.setText("2.Permit");

        searchButtonSet.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButton8.setText("3.Grant");

        searchButtonSet.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButton9.setText("4.Grama Niladari Division");

        searchButtonSet.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButton10.setText("5.Available lands");

        applicantSearchSet.add(jCheckBox13);
        jCheckBox13.setText("By name");

        applicantSearchSet.add(jCheckBox14);
        jCheckBox14.setText("By NIC");

        applicantSearchSet.add(jCheckBox15);
        jCheckBox15.setText("By GND");

        permitSearchSet.add(jCheckBox16);
        jCheckBox16.setText("By permit number");

        permitSearchSet.add(jCheckBox17);
        jCheckBox17.setText("By applicant name");

        permitSearchSet.add(jCheckBox18);
        jCheckBox18.setText("By NIC");

        grantSearchSet.add(jCheckBox19);
        jCheckBox19.setText("By permit number");

        grantSearchSet.add(jCheckBox20);
        jCheckBox20.setText("By grant number");

        grantSearchSet.add(jCheckBox21);
        jCheckBox21.setText("By applicant name");

        grantSearchSet.add(jCheckBox22);
        jCheckBox22.setText("By NIC");

        landSearchSet.add(jCheckBox23);
        jCheckBox23.setText("All lands");

        landSearchSet.add(jCheckBox24);
        jCheckBox24.setText("By A Division");

        javax.swing.GroupLayout searchPanel1Layout = new javax.swing.GroupLayout(searchPanel1);
        searchPanel1.setLayout(searchPanel1Layout);
        searchPanel1Layout.setHorizontalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton9)
                            .addGroup(searchPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox14)
                                    .addComponent(jCheckBox13)
                                    .addComponent(jCheckBox15)
                                    .addComponent(jCheckBox18)
                                    .addComponent(jCheckBox16)
                                    .addComponent(jCheckBox17)
                                    .addComponent(jCheckBox19)
                                    .addComponent(jCheckBox20)
                                    .addComponent(jCheckBox21)
                                    .addComponent(jCheckBox22))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton10)
                    .addGroup(searchPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox23)
                            .addComponent(jCheckBox24))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPanel1Layout.setVerticalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("     Siyora Tuition Management system");

        jLabel3.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel3.setText("classes for grade 3 , 4 and 5 targeting grade 5 schoolarship examination");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        userpanel.setBackground(new java.awt.Color(102, 102, 0));

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        LogOutButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/icons/logOff.png"))); // NOI18N
        LogOutButton.setText("Log off");
        LogOutButton.setToolTipText("Log-off");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LogOutButton);

        ExitButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/icons/exit.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setToolTipText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ExitButton);

        javax.swing.GroupLayout userpanelLayout = new javax.swing.GroupLayout(userpanel);
        userpanel.setLayout(userpanelLayout);
        userpanelLayout.setHorizontalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addContainerGap())
        );
        userpanelLayout.setVerticalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userpanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout userLogPanelLayout = new javax.swing.GroupLayout(userLogPanel);
        userLogPanel.setLayout(userLogPanelLayout);
        userLogPanelLayout.setHorizontalGroup(
            userLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLogPanelLayout.createSequentialGroup()
                .addComponent(userpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        userLogPanelLayout.setVerticalGroup(
            userLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLogPanelLayout.createSequentialGroup()
                .addComponent(userpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        searchPanel.setBackground(new java.awt.Color(102, 102, 0));
        searchPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Search Result");

        searchSetCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Paper", "Schoolarshipresult", " " }));
        searchSetCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchSetComboItemStateChanged(evt);
            }
        });
        searchSetCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSetComboActionPerformed(evt);
            }
        });

        goButton.setText("Go ");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setText("-A Product By GeninSoft-");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(searchSetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(searchPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(17, 17, 17)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(searchSetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(goButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        desktopPane.setBackground(new java.awt.Color(255, 153, 153));
        desktopPane.setForeground(new java.awt.Color(255, 153, 153));
        desktopPane.setOpaque(false);
        desktopPane.setPreferredSize(new java.awt.Dimension(581, 581));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        desktopPane.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout internalFrameAreaPanelLayout = new javax.swing.GroupLayout(internalFrameAreaPanel);
        internalFrameAreaPanel.setLayout(internalFrameAreaPanelLayout);
        internalFrameAreaPanelLayout.setHorizontalGroup(
            internalFrameAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalFrameAreaPanelLayout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addContainerGap())
        );
        internalFrameAreaPanelLayout.setVerticalGroup(
            internalFrameAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalFrameAreaPanelLayout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        shortcutAccessPanel.setBackground(new java.awt.Color(102, 102, 102));
        shortcutAccessPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        shortcutAccessPanel.setLayout(new java.awt.GridLayout(7, 1, 50, 10));

        studentRestrationFB.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        studentRestrationFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/icons/applicant - s.png"))); // NOI18N
        studentRestrationFB.setText("1-Student Registration");
        importantButtonSet.add(studentRestrationFB);
        studentRestrationFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRestrationFBActionPerformed(evt);
            }
        });
        shortcutAccessPanel.add(studentRestrationFB);

        addNewStudentMarkMB.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        addNewStudentMarkMB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/icons/exam.png"))); // NOI18N
        addNewStudentMarkMB.setText("2-Add Student Mark");
        importantButtonSet.add(addNewStudentMarkMB);
        addNewStudentMarkMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStudentMarkMBActionPerformed(evt);
            }
        });
        shortcutAccessPanel.add(addNewStudentMarkMB);

        markAtendenceFB.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        markAtendenceFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/icons/attendence.png"))); // NOI18N
        markAtendenceFB.setText("3-Mark Attendence");
        importantButtonSet.add(markAtendenceFB);
        markAtendenceFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAtendenceFBActionPerformed(evt);
            }
        });
        shortcutAccessPanel.add(markAtendenceFB);

        addClassFeesFB.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        addClassFeesFB.setText("4-Add ClassFees");
        importantButtonSet.add(addClassFeesFB);
        addClassFeesFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassFeesFBActionPerformed(evt);
            }
        });
        shortcutAccessPanel.add(addClassFeesFB);

        addSchoolarshipMarksFB.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        addSchoolarshipMarksFB.setText("5-Add Schoolarship Marks");
        importantButtonSet.add(addSchoolarshipMarksFB);
        addSchoolarshipMarksFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSchoolarshipMarksFBActionPerformed(evt);
            }
        });
        shortcutAccessPanel.add(addSchoolarshipMarksFB);

        sendNotifaicationFB.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        sendNotifaicationFB.setText("6-Send Notification");
        importantButtonSet.add(sendNotifaicationFB);
        sendNotifaicationFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNotifaicationFBActionPerformed(evt);
            }
        });
        shortcutAccessPanel.add(sendNotifaicationFB);

        viewStudentMarksFB.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        viewStudentMarksFB.setText("7-View Student Marks");
        importantButtonSet.add(viewStudentMarksFB);
        viewStudentMarksFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentMarksFBActionPerformed(evt);
            }
        });
        shortcutAccessPanel.add(viewStudentMarksFB);

        javax.swing.GroupLayout desktopJPanelLayout = new javax.swing.GroupLayout(desktopJPanel);
        desktopJPanel.setLayout(desktopJPanelLayout);
        desktopJPanelLayout.setHorizontalGroup(
            desktopJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopJPanelLayout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(desktopJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopJPanelLayout.createSequentialGroup()
                        .addComponent(internalFrameAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shortcutAccessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopJPanelLayout.createSequentialGroup()
                        .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        desktopJPanelLayout.setVerticalGroup(
            desktopJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopJPanelLayout.createSequentialGroup()
                .addGroup(desktopJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userLogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(desktopJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(desktopJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(internalFrameAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(shortcutAccessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setText("Student");

        addStudentDetailM.setText("Add Student Detail");
        addStudentDetailM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentDetailMActionPerformed(evt);
            }
        });
        jMenu1.add(addStudentDetailM);

        registerStudentM.setText("Register Student");
        registerStudentM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerStudentMActionPerformed(evt);
            }
        });
        jMenu1.add(registerStudentM);

        editStudentDetail.setText("Edit Student Detail");
        editStudentDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentDetailActionPerformed(evt);
            }
        });
        jMenu1.add(editStudentDetail);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Class");

        addNewClassM.setText("Add New Class");
        addNewClassM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewClassMActionPerformed(evt);
            }
        });
        jMenu2.add(addNewClassM);

        editClassDetailM.setText("Edit Class Detail");
        editClassDetailM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClassDetailMActionPerformed(evt);
            }
        });
        jMenu2.add(editClassDetailM);

        jMenuBar1.add(jMenu2);

        Grant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/icons/examM.png"))); // NOI18N
        Grant.setText("Student Mark");

        addNewPaperM.setText("Add Student Mark");
        addNewPaperM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPaperMActionPerformed(evt);
            }
        });
        Grant.add(addNewPaperM);

        addPaperMarksM.setText("Add Paper Marks");
        addPaperMarksM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaperMarksMActionPerformed(evt);
            }
        });
        Grant.add(addPaperMarksM);

        viewResultM.setText("View Result");
        viewResultM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResultMActionPerformed(evt);
            }
        });
        Grant.add(viewResultM);

        jMenuBar1.add(Grant);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/icons/attendenceM.png"))); // NOI18N
        jMenu3.setText("Attendence");

        addAttendenceM.setText("Add Attendence");
        addAttendenceM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAttendenceMActionPerformed(evt);
            }
        });
        jMenu3.add(addAttendenceM);

        editAttendenceM.setText("Edit Attendence");
        editAttendenceM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAttendenceMActionPerformed(evt);
            }
        });
        jMenu3.add(editAttendenceM);

        viewAttendenceM.setText("View Attendence");
        viewAttendenceM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttendenceMActionPerformed(evt);
            }
        });
        jMenu3.add(viewAttendenceM);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("ClassFees");

        jMenu5.setText("Add New ClassFeesId");
        jMenu4.add(jMenu5);

        jMenuBar1.add(jMenu4);

        systemMenu.setText("System");

        changePasswordMenu.setText("Change password");
        changePasswordMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordMenuActionPerformed(evt);
            }
        });
        systemMenu.add(changePasswordMenu);

        createNewUserMenu.setText("Create new user");
        createNewUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewUserMenuActionPerformed(evt);
            }
        });
        systemMenu.add(createNewUserMenu);

        viewAllUsersMenu.setText("View all users");
        viewAllUsersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllUsersMenuActionPerformed(evt);
            }
        });
        systemMenu.add(viewAllUsersMenu);
        systemMenu.add(jSeparator1);

        backUpMenu.setText("Create a backup");
        backUpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backUpMenuActionPerformed(evt);
            }
        });
        systemMenu.add(backUpMenu);

        restoreMenu.setText("Restore backup");
        restoreMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreMenuActionPerformed(evt);
            }
        });
        systemMenu.add(restoreMenu);

        jMenuBar1.add(systemMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentRestrationFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRestrationFBActionPerformed
        StudentRegistration studentRegistrationForm = new StudentRegistration(this);
        studentRegistrationForm.setSize(desktopPane.getSize());
        desktopPane.removeAll();
        desktopPane.add(studentRegistrationForm);
        studentRegistrationForm.setVisible(true);
        studentRegistrationForm.requestFocus();
    }//GEN-LAST:event_studentRestrationFBActionPerformed


    private void sendNotifaicationFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNotifaicationFBActionPerformed
    }//GEN-LAST:event_sendNotifaicationFBActionPerformed

    private void addClassFeesFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassFeesFBActionPerformed
        ClassFeesManagement classFeesManagement = new ClassFeesManagement(this, true);
        classFeesManagement.setLocationRelativeTo(null);
        classFeesManagement.setVisible(true);
    }//GEN-LAST:event_addClassFeesFBActionPerformed

    private void addNewStudentMarkMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStudentMarkMBActionPerformed
        StudentMarkManagement studentMarkManagement = new StudentMarkManagement(this, true);
        studentMarkManagement.setLocationRelativeTo(null);
        studentMarkManagement.setVisible(true);


    }//GEN-LAST:event_addNewStudentMarkMBActionPerformed

    private void markAtendenceFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAtendenceFBActionPerformed
        AttendenceManagement attendenceManagement = new AttendenceManagement(this, true);
        attendenceManagement.setLocationRelativeTo(null);
        attendenceManagement.setVisible(true);
    }//GEN-LAST:event_markAtendenceFBActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        switch (searchSetCombo.getSelectedIndex()) {
            case 1:
                ResultbyPapers resultbyPapers = new ResultbyPapers(this, true);
                resultbyPapers.setLocationRelativeTo(null);
                resultbyPapers.setVisible(true);
                break;
            case 0:
                ResultbyStudent resultbyStudent = new ResultbyStudent(this, true);
                resultbyStudent.setLocationRelativeTo(null);
                resultbyStudent.setVisible(true);
                break;
            case 2:
                ResultbyClass resultbyClass = new ResultbyClass(this,true);
                resultbyClass.setLocationRelativeTo(null);
                resultbyClass.setVisible(true);
                break;
            default:
                break;
        }

    }//GEN-LAST:event_goButtonActionPerformed

    private void searchSetComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchSetComboItemStateChanged
    }//GEN-LAST:event_searchSetComboItemStateChanged

    private void addSchoolarshipMarksFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSchoolarshipMarksFBActionPerformed
        SchoolarshipMarkManagement schoolarshipMarkManagement = new SchoolarshipMarkManagement(this, true);
        schoolarshipMarkManagement.setLocationRelativeTo(null);
        schoolarshipMarkManagement.setVisible(true);
        //new PermitCertificationForm(this, true).setVisible(true);
    }//GEN-LAST:event_addSchoolarshipMarksFBActionPerformed

    private void searchSetComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSetComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSetComboActionPerformed

    private void viewResultMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResultMActionPerformed
    }//GEN-LAST:event_viewResultMActionPerformed

    private void addPaperMarksMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaperMarksMActionPerformed
    }//GEN-LAST:event_addPaperMarksMActionPerformed

    private void backUpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backUpMenuActionPerformed
    }//GEN-LAST:event_backUpMenuActionPerformed

    private void restoreMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreMenuActionPerformed
    }//GEN-LAST:event_restoreMenuActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void changePasswordMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordMenuActionPerformed
    }//GEN-LAST:event_changePasswordMenuActionPerformed

    private void createNewUserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewUserMenuActionPerformed
    }//GEN-LAST:event_createNewUserMenuActionPerformed

    private void viewAllUsersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllUsersMenuActionPerformed
    }//GEN-LAST:event_viewAllUsersMenuActionPerformed

    private void addNewPaperMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPaperMActionPerformed
    }//GEN-LAST:event_addNewPaperMActionPerformed

    private void addAttendenceMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAttendenceMActionPerformed
    }//GEN-LAST:event_addAttendenceMActionPerformed

    private void viewAttendenceMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttendenceMActionPerformed
    }//GEN-LAST:event_viewAttendenceMActionPerformed

    private void addStudentDetailMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentDetailMActionPerformed
        StudentDetail studentDetail = new StudentDetail(this, true);
        studentDetail.setLocationRelativeTo(null);
        studentDetail.setVisible(true);

    }//GEN-LAST:event_addStudentDetailMActionPerformed

    private void registerStudentMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerStudentMActionPerformed
    }//GEN-LAST:event_registerStudentMActionPerformed

    private void editStudentDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentDetailActionPerformed
    }//GEN-LAST:event_editStudentDetailActionPerformed

    private void editAttendenceMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAttendenceMActionPerformed
    }//GEN-LAST:event_editAttendenceMActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
    }//GEN-LAST:event_formKeyReleased


    private void viewStudentMarksFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentMarksFBActionPerformed
    }//GEN-LAST:event_viewStudentMarksFBActionPerformed

    private void editClassDetailMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClassDetailMActionPerformed

        ClassDetail classDetail = new ClassDetail(this, true, 1);
        classDetail.setLocationRelativeTo(null);
        classDetail.setVisible(true);

    }//GEN-LAST:event_editClassDetailMActionPerformed

    private void addNewClassMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewClassMActionPerformed

        ClassDetail classDetail = new ClassDetail(this, true, 0);
        classDetail.setLocationRelativeTo(null);
        classDetail.setVisible(true);
    }//GEN-LAST:event_addNewClassMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrontPage fp = new FrontPage();
                fp.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JMenu Grant;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JMenuItem addAttendenceM;
    private javax.swing.JButton addClassFeesFB;
    private javax.swing.JMenuItem addNewClassM;
    private javax.swing.JMenuItem addNewPaperM;
    private javax.swing.JButton addNewStudentMarkMB;
    private javax.swing.JMenuItem addPaperMarksM;
    private javax.swing.JButton addSchoolarshipMarksFB;
    private javax.swing.JMenuItem addStudentDetailM;
    private javax.swing.ButtonGroup applicantSearchSet;
    private javax.swing.JMenuItem backUpMenu;
    private javax.swing.JMenuItem changePasswordMenu;
    private javax.swing.JMenuItem createNewUserMenu;
    private javax.swing.JPanel desktopJPanel;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem editAttendenceM;
    private javax.swing.JMenuItem editClassDetailM;
    private javax.swing.JMenuItem editStudentDetail;
    private javax.swing.JButton goButton;
    private javax.swing.ButtonGroup grantSearchSet;
    private javax.swing.ButtonGroup importantButtonSet;
    private javax.swing.JPanel internalFrameAreaPanel;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.ButtonGroup landSearchSet;
    private javax.swing.JButton markAtendenceFB;
    private javax.swing.ButtonGroup permitSearchSet;
    private javax.swing.JMenuItem registerStudentM;
    private javax.swing.JMenuItem restoreMenu;
    private javax.swing.ButtonGroup searchButtonSet;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel searchPanel1;
    private javax.swing.JComboBox searchSetCombo;
    private javax.swing.JButton sendNotifaicationFB;
    private javax.swing.JPanel shortcutAccessPanel;
    private javax.swing.JButton studentRestrationFB;
    private javax.swing.JMenu systemMenu;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel userLogPanel;
    private javax.swing.JLabel username;
    private javax.swing.JPanel userpanel;
    private javax.swing.JMenuItem viewAllUsersMenu;
    private javax.swing.JMenuItem viewAttendenceM;
    private javax.swing.JMenuItem viewResultM;
    private javax.swing.JButton viewStudentMarksFB;
    // End of variables declaration//GEN-END:variables
}
