/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tms.views;

import SeverConnector.Connector;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import tms.controllercommon.ClassController;
import tms.controllercommon.ExamController;
import tms.controllercommon.PaperController;
import tms.controllercommon.RegistrationController;
import tms.controllercommon.SchoolarshipResultController;
import tms.controllercommon.StudentController;
import tms.model.ClassS;
import tms.model.Exam;
import tms.model.Paper;
import tms.model.SchoolarshipResult;
import tms.model.Student;

/**
 *
 * @author Gimhani Uthpala
 */
public class SchoolarshipMarkManagement extends javax.swing.JDialog {

    RegistrationController registrationController;
    ClassController classController;
    StudentController studentController;
    SchoolarshipResultController schoolarshipResultController;
    

    /**
     * Creates new form StudentMarkManagement
     */
    public SchoolarshipMarkManagement(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            Connector sConnector = Connector.getSConnector();
            registrationController = sConnector.getRegistrationController();
            classController = sConnector.getClassController();
            studentController = sConnector.getStudentController();
            schoolarshipResultController=sConnector.getSchoolarshipResultController();
           
        } catch (SQLException | ClassNotFoundException | NotBoundException | MalformedURLException | RemoteException | InterruptedException ex) {
            Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        loadClassCombo();
        loadIndexCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        classIdAddMarkL = new javax.swing.JLabel();
        classIdComboA = new javax.swing.JComboBox<>();
        studentIdCombo = new javax.swing.JComboBox<>();
        classIdAddMarkL1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addMarkB = new javax.swing.JButton();
        nameRL = new javax.swing.JLabel();
        nameTA = new javax.swing.JTextField();
        birthdayRL = new javax.swing.JLabel();
        indexNumberTA = new javax.swing.JTextField();
        parentRL = new javax.swing.JLabel();
        resultTA = new javax.swing.JTextField();
        contactNumberRL = new javax.swing.JLabel();
        rankTA = new javax.swing.JTextField();
        contactNumberRL1 = new javax.swing.JLabel();
        yearComboA = new javax.swing.JComboBox<>();
        contactNumberRL2 = new javax.swing.JLabel();
        yesBA = new javax.swing.JRadioButton();
        NoBA = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        classIdAddMarkL2 = new javax.swing.JLabel();
        indexComboE = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        editMarkB = new javax.swing.JButton();
        nameRL1 = new javax.swing.JLabel();
        nameTE = new javax.swing.JTextField();
        birthdayRL1 = new javax.swing.JLabel();
        studentIdTE = new javax.swing.JTextField();
        parentRL1 = new javax.swing.JLabel();
        resultTE = new javax.swing.JTextField();
        contactNumberRL3 = new javax.swing.JLabel();
        rankTE = new javax.swing.JTextField();
        contactNumberRL4 = new javax.swing.JLabel();
        contactNumberRL5 = new javax.swing.JLabel();
        yesBE = new javax.swing.JRadioButton();
        NoBE = new javax.swing.JRadioButton();
        yearTE = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        viewByC = new javax.swing.JComboBox<>();
        loadB = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classIdAddMarkL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classIdAddMarkL.setText("Class Id");

        classIdComboA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                classIdComboAItemStateChanged(evt);
            }
        });
        classIdComboA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classIdComboAActionPerformed(evt);
            }
        });

        studentIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentIdComboItemStateChanged(evt);
            }
        });
        studentIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdComboActionPerformed(evt);
            }
        });

        classIdAddMarkL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classIdAddMarkL1.setText("Student Id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 61, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classIdComboA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIdCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classIdAddMarkL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classIdAddMarkL1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classIdAddMarkL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classIdComboA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(classIdAddMarkL1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addMarkB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        addMarkB.setText("Add Mark");
        addMarkB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarkBActionPerformed(evt);
            }
        });

        nameRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        nameRL.setText("Student Name");

        nameTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTAActionPerformed(evt);
            }
        });

        birthdayRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        birthdayRL.setText("Index Number");

        indexNumberTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexNumberTAActionPerformed(evt);
            }
        });

        parentRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        parentRL.setText("Result");

        resultTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTAActionPerformed(evt);
            }
        });

        contactNumberRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL.setText("Rank");

        contactNumberRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL1.setText("Year");

        yearComboA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }));

        contactNumberRL2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL2.setText("Pass");

        yesBA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        yesBA.setText("Yes");

        NoBA.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        NoBA.setText("No");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactNumberRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(parentRL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberRL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberRL2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(yesBA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NoBA))
                                    .addComponent(rankTA)
                                    .addComponent(resultTA)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameRL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdayRL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTA, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(indexNumberTA)
                            .addComponent(yearComboA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addMarkB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameRL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayRL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexNumberTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearComboA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parentRL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberRL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rankTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberRL2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yesBA)
                    .addComponent(NoBA))
                .addGap(18, 18, 18)
                .addComponent(addMarkB)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Schoolarship Mark", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classIdAddMarkL2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        classIdAddMarkL2.setText("Index Number");

        indexComboE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                indexComboEItemStateChanged(evt);
            }
        });
        indexComboE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexComboEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(indexComboE, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classIdAddMarkL2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classIdAddMarkL2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indexComboE, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        editMarkB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        editMarkB.setText("Edit Mark");
        editMarkB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMarkBActionPerformed(evt);
            }
        });

        nameRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        nameRL1.setText("Student Name");

        nameTE.setEditable(false);
        nameTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTEActionPerformed(evt);
            }
        });

        birthdayRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        birthdayRL1.setText("Student Id");

        studentIdTE.setEditable(false);
        studentIdTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdTEActionPerformed(evt);
            }
        });

        parentRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        parentRL1.setText("Result");

        resultTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTEActionPerformed(evt);
            }
        });

        contactNumberRL3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL3.setText("Rank");

        contactNumberRL4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL4.setText("Year");

        contactNumberRL5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL5.setText("Pass");

        yesBE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        yesBE.setText("Yes");

        NoBE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        NoBE.setText("No");

        yearTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactNumberRL4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(parentRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberRL3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberRL5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(yesBE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NoBE))
                                    .addComponent(rankTE)
                                    .addComponent(resultTE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdayRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTE, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(studentIdTE)
                            .addComponent(yearTE))))
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(editMarkB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentIdTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberRL4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parentRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberRL3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rankTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberRL5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yesBE)
                    .addComponent(NoBE))
                .addGap(18, 18, 18)
                .addComponent(editMarkB)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edit Schoolarship  Mark", jPanel4);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel1.setText("View By");

        viewByC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        viewByC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "all result", "by year" }));

        loadB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        loadB.setText("Load");
        loadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(viewByC, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(loadB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewByC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(loadB)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        desktopPane.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("View result", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classIdComboAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classIdComboAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classIdComboAActionPerformed

    private void addMarkBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarkBActionPerformed
        try {
            String studentId = String.valueOf(studentIdCombo.getSelectedItem());
            int indexNumber = Integer.parseInt(indexNumberTA.getText());
            int result = Integer.parseInt(resultTA.getText());
            int rank = Integer.parseInt(rankTA.getText());            
            int pass=0;
            if(yesBA.isSelected()){
                pass=1;
            }
            int year = Integer.parseInt(String.valueOf(yearComboA.getSelectedItem()));
            Student student = studentController.searchStudent(studentId);
            SchoolarshipResult schoolarshipResult = new SchoolarshipResult(student, indexNumber, year, result, rank, pass);
            boolean addSchoolarshipResult = schoolarshipResultController.addSchoolarshipResult(schoolarshipResult);
            if(addSchoolarshipResult){
                JOptionPane.showMessageDialog(this,"result is added successfully");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"result is not added successfully");
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addMarkBActionPerformed

    private void studentIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdComboActionPerformed

    private void nameTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTAActionPerformed

    private void indexNumberTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexNumberTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexNumberTAActionPerformed

    private void resultTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTAActionPerformed

    private void indexComboEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexComboEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexComboEActionPerformed

    private void editMarkBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMarkBActionPerformed
        try {
            String studentId = studentIdTE.getText();
            int indexNumber = Integer.parseInt(String.valueOf(indexComboE.getSelectedItem()));
            int result = Integer.parseInt(resultTE.getText());
            int rank = Integer.parseInt(rankTE.getText());            
            int pass=0;
            if(yesBE.isSelected()){
                pass=1;
            }
            int year = Integer.parseInt(yearTE.getText());
            Student student = studentController.searchStudent(studentId);
            SchoolarshipResult schoolarshipResult = new SchoolarshipResult(student, indexNumber, year, result, rank, pass);
            boolean editSchoolarshipResult = schoolarshipResultController.editSchoolarshipResult(schoolarshipResult);
            if(editSchoolarshipResult){
                JOptionPane.showMessageDialog(this,"result is updated successfully");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"result is not updated successfully");
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        
    }//GEN-LAST:event_editMarkBActionPerformed

    private void nameTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTEActionPerformed

    private void studentIdTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdTEActionPerformed

    private void resultTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTEActionPerformed

    private void classIdComboAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_classIdComboAItemStateChanged
        String classId = String.valueOf(classIdComboA.getSelectedItem());
        loadStudentIdOfClass(classId);
    }//GEN-LAST:event_classIdComboAItemStateChanged

    private void studentIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentIdComboItemStateChanged
        try {
            String studentId = String.valueOf(studentIdCombo.getSelectedItem());
            Student searchStudent = studentController.searchStudent(studentId);
            nameTA.setText(searchStudent.getName());
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentIdComboItemStateChanged

    private void indexComboEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_indexComboEItemStateChanged
        String index =String.valueOf(indexComboE.getSelectedItem());
        try {
            SchoolarshipResult searchSchoolarshipResult = schoolarshipResultController.searchSchoolarshipResult(index);
            nameTE.setText(searchSchoolarshipResult.getStudent().getName());
            studentIdTE.setText(searchSchoolarshipResult.getStudent().getStudentId());
            resultTE.setText(String.valueOf(searchSchoolarshipResult.getResult()));
            rankTE.setText(String.valueOf(searchSchoolarshipResult.getRank()));
            yearTE.setText(String.valueOf(searchSchoolarshipResult.getYear()));
            int isPass = searchSchoolarshipResult.getIsPass();
            if(isPass==0){
                NoBE.setSelected(true);
            }else{
                yesBE.setSelected(true);
             }
        } catch (RemoteException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_indexComboEItemStateChanged

    private void yearTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTEActionPerformed

    private void loadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBActionPerformed
        
        
        int selectedIndex = viewByC.getSelectedIndex();
        if (selectedIndex == 0) {
            SchoolarshipMarkOverall schoolarshipMarkOverall = new SchoolarshipMarkOverall();
            schoolarshipMarkOverall.setSize(desktopPane.getSize());
            desktopPane.removeAll();
            desktopPane.add(schoolarshipMarkOverall);
            schoolarshipMarkOverall.setVisible(true);
            schoolarshipMarkOverall.requestFocus();
        } else {
            
            SchoolarshipMarkByYear schoolarshipMarkByYear = new SchoolarshipMarkByYear();
            schoolarshipMarkByYear.setSize(desktopPane.getSize());
            desktopPane.removeAll();
            desktopPane.add(schoolarshipMarkByYear);
            schoolarshipMarkByYear.setVisible(true);
            schoolarshipMarkByYear.requestFocus();
            
        }

  

    }//GEN-LAST:event_loadBActionPerformed

    
    private void loadClassCombo() {
        classIdComboA.removeAllItems();
        try {
            ArrayList<ClassS> allClass = classController.getAllClass();
            for (ClassS cls : allClass) {
                classIdComboA.addItem(cls.getClassId());
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
   
    private void loadIndexCombo() {
        indexComboE.removeAllItems();
        try {
            ArrayList<SchoolarshipResult> allSchoolarshipResult = schoolarshipResultController.getAllSchoolarshipResult();
            for (SchoolarshipResult schoolarshipResult : allSchoolarshipResult) {
                indexComboE.addItem(String.valueOf(schoolarshipResult.getIndexNumber()));
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
  
    
    private void loadStudentIdOfClass(String classId) {
        try {
            studentIdCombo.removeAllItems();
            ArrayList<Student> studentOfClass = registrationController.getStudentOfClass(classId);
            for (Student student : studentOfClass) {
                studentIdCombo.addItem(student.getStudentId());
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ClassFeesManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolarshipMarkManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SchoolarshipMarkManagement dialog = new SchoolarshipMarkManagement(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NoBA;
    private javax.swing.JRadioButton NoBE;
    private javax.swing.JButton addMarkB;
    private javax.swing.JLabel birthdayRL;
    private javax.swing.JLabel birthdayRL1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel classIdAddMarkL;
    private javax.swing.JLabel classIdAddMarkL1;
    private javax.swing.JLabel classIdAddMarkL2;
    private javax.swing.JComboBox<String> classIdComboA;
    private javax.swing.JLabel contactNumberRL;
    private javax.swing.JLabel contactNumberRL1;
    private javax.swing.JLabel contactNumberRL2;
    private javax.swing.JLabel contactNumberRL3;
    private javax.swing.JLabel contactNumberRL4;
    private javax.swing.JLabel contactNumberRL5;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton editMarkB;
    private javax.swing.JComboBox<String> indexComboE;
    private javax.swing.JTextField indexNumberTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loadB;
    private javax.swing.JLabel nameRL;
    private javax.swing.JLabel nameRL1;
    private javax.swing.JTextField nameTA;
    private javax.swing.JTextField nameTE;
    private javax.swing.JLabel parentRL;
    private javax.swing.JLabel parentRL1;
    private javax.swing.JTextField rankTA;
    private javax.swing.JTextField rankTE;
    private javax.swing.JTextField resultTA;
    private javax.swing.JTextField resultTE;
    private javax.swing.JComboBox<String> studentIdCombo;
    private javax.swing.JTextField studentIdTE;
    private javax.swing.JComboBox<String> viewByC;
    private javax.swing.JComboBox<String> yearComboA;
    private javax.swing.JTextField yearTE;
    private javax.swing.JRadioButton yesBA;
    private javax.swing.JRadioButton yesBE;
    // End of variables declaration//GEN-END:variables
}
