/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tms.views;

import SeverConnector.Connector;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tms.controllercommon.StudentController;
import tms.model.Student;

/**
 *
 * @author Nuwantha
 */
public class StudentDetail extends javax.swing.JDialog {
     StudentController studentController;
    /**
     * Creates new form NewJDialog
     */
     
     
    public StudentDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
         try {
             studentController=Connector.getSConnector().getStudentController();
         } catch (SQLException | InterruptedException | ClassNotFoundException | NotBoundException | MalformedURLException | RemoteException ex) {
             Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         setStudentID();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        indexNumberRL = new javax.swing.JLabel();
        nameRL = new javax.swing.JLabel();
        birthdayRL = new javax.swing.JLabel();
        addressRL = new javax.swing.JLabel();
        parentRL = new javax.swing.JLabel();
        contactNumberRL = new javax.swing.JLabel();
        nameRT = new javax.swing.JTextField();
        birthdayRT = new javax.swing.JTextField();
        parentRT = new javax.swing.JTextField();
        contactNumberRT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressRT = new javax.swing.JTextArea();
        addStudentB = new javax.swing.JButton();
        indexNumberRT = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        indexNumberRL1 = new javax.swing.JLabel();
        nameRL1 = new javax.swing.JLabel();
        birthdayRL1 = new javax.swing.JLabel();
        addressRL1 = new javax.swing.JLabel();
        parentRL1 = new javax.swing.JLabel();
        contactNumberRL1 = new javax.swing.JLabel();
        nameET = new javax.swing.JTextField();
        birthdayET = new javax.swing.JTextField();
        parentET = new javax.swing.JTextField();
        contactNumberET = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressET = new javax.swing.JTextArea();
        editStudentB = new javax.swing.JButton();
        indexNumberET = new javax.swing.JTextField();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        indexNumberRL2 = new javax.swing.JLabel();
        nameRL2 = new javax.swing.JLabel();
        birthdayRL2 = new javax.swing.JLabel();
        addressRL2 = new javax.swing.JLabel();
        parentRL2 = new javax.swing.JLabel();
        contactNumberRL2 = new javax.swing.JLabel();
        nameDT = new javax.swing.JTextField();
        birthdayDT = new javax.swing.JTextField();
        parentDT = new javax.swing.JTextField();
        contactNumberDT = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        addressDT = new javax.swing.JTextArea();
        deleteStudentB = new javax.swing.JButton();
        indexNumberDT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        indexNumberRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        indexNumberRL.setText("Index Number");

        nameRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        nameRL.setText("Name");

        birthdayRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        birthdayRL.setText("Birthday");

        addressRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        addressRL.setText("Address");

        parentRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        parentRL.setText("Parent");

        contactNumberRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL.setText("Contact Number");

        nameRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRTActionPerformed(evt);
            }
        });

        birthdayRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayRTActionPerformed(evt);
            }
        });

        addressRT.setColumns(20);
        addressRT.setRows(5);
        jScrollPane1.setViewportView(addressRT);

        addStudentB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        addStudentB.setText("Add Student");
        addStudentB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBActionPerformed(evt);
            }
        });

        indexNumberRT.setEditable(false);
        indexNumberRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexNumberRTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(indexNumberRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(birthdayRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parentRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactNumberRL, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addStudentB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameRT)
                    .addComponent(birthdayRT)
                    .addComponent(parentRT)
                    .addComponent(contactNumberRT)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(indexNumberRT))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(indexNumberRL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexNumberRT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameRT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayRL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayRT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressRL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parentRT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentRL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberRL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumberRT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(addStudentB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Add Student", jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        indexNumberRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        indexNumberRL1.setText("Index Number");

        nameRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        nameRL1.setText("Name");

        birthdayRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        birthdayRL1.setText("Birthday");

        addressRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        addressRL1.setText("Address");

        parentRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        parentRL1.setText("Parent");

        contactNumberRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL1.setText("Contact Number");

        nameET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameETActionPerformed(evt);
            }
        });

        birthdayET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayETActionPerformed(evt);
            }
        });

        addressET.setColumns(20);
        addressET.setRows(5);
        jScrollPane2.setViewportView(addressET);

        editStudentB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        editStudentB.setText("Edit Student");

        indexNumberET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexNumberETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(indexNumberRL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameRL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(birthdayRL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressRL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parentRL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactNumberRL1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editStudentB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameET)
                    .addComponent(birthdayET)
                    .addComponent(parentET)
                    .addComponent(contactNumberET)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(indexNumberET))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(indexNumberRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexNumberET, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameET, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayET, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parentET, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumberET, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editStudentB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Edit Student", jPanel6);
        jTabbedPane1.addTab("tab3", jTabbedPane4);
        jTabbedPane1.addTab("tab3", jTabbedPane3);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        indexNumberRL2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        indexNumberRL2.setText("Index Number");

        nameRL2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        nameRL2.setText("Name");

        birthdayRL2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        birthdayRL2.setText("Birthday");

        addressRL2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        addressRL2.setText("Address");

        parentRL2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        parentRL2.setText("Parent");

        contactNumberRL2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL2.setText("Contact Number");

        nameDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameDTActionPerformed(evt);
            }
        });

        birthdayDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayDTActionPerformed(evt);
            }
        });

        addressDT.setColumns(20);
        addressDT.setRows(5);
        jScrollPane3.setViewportView(addressDT);

        deleteStudentB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        deleteStudentB.setText("Delete Student");

        indexNumberDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexNumberDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(indexNumberRL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameRL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(birthdayRL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressRL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parentRL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactNumberRL2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteStudentB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameDT)
                    .addComponent(birthdayDT)
                    .addComponent(parentDT)
                    .addComponent(contactNumberDT)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(indexNumberDT))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(indexNumberRL2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexNumberDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRL2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayRL2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayDT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressRL2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parentDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentRL2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberRL2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumberDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(deleteStudentB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Delete Student", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Add Student");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRTActionPerformed

    private void birthdayRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayRTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayRTActionPerformed

    private void indexNumberRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexNumberRTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexNumberRTActionPerformed

    private void nameETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameETActionPerformed

    private void birthdayETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayETActionPerformed

    private void indexNumberETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexNumberETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexNumberETActionPerformed

    private void nameDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameDTActionPerformed

    private void birthdayDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayDTActionPerformed

    private void indexNumberDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexNumberDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexNumberDTActionPerformed

    private void addStudentBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBActionPerformed
         
        String studentId = indexNumberRT.getText();
        String name = nameRT.getText();
        String birthday= birthdayRT.getText();
        String address=addressRT.getText();
        String parent = parentRT.getText();
        String contactNumber=contactNumberRT.getText();
        
         Student student = new Student(studentId, birthday, name, address, parent, contactNumber);
         try {
            boolean addNewStudent = studentController.addNewStudent(student);
            if(addNewStudent){
                JOptionPane.showMessageDialog(this,"student are added succesfully");
                setStudentID();
                nameRT.setText("");
                birthdayRT.setText("");
                addressRT.setText("");
                parentRT.setText("");
                contactNumberRT.setText("");
            }else{
                JOptionPane.showMessageDialog(this,"student are not added successfully");
            }
         } catch (RemoteException | SQLException | ClassNotFoundException ex) {
             Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
                  
    }//GEN-LAST:event_addStudentBActionPerformed
    
    private void setStudentID(){
         try {
            int studentCount = studentController.getStudentCount()+1;
            if(studentCount<10){
                indexNumberRT.setText("St000"+String.valueOf(studentCount)  );
            }else if(studentCount<100){
                indexNumberRT.setText("St00"+String.valueOf(studentCount)  );
            }else if(studentCount<1000){
                indexNumberRT.setText("St0"+String.valueOf(studentCount)  );
            }else{
                indexNumberRT.setText("St"+String.valueOf(studentCount)  );
            }
         } catch (RemoteException | SQLException | ClassNotFoundException ex) {
             Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentDetail dialog = new StudentDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentB;
    private javax.swing.JTextArea addressDT;
    private javax.swing.JTextArea addressET;
    private javax.swing.JLabel addressRL;
    private javax.swing.JLabel addressRL1;
    private javax.swing.JLabel addressRL2;
    private javax.swing.JTextArea addressRT;
    private javax.swing.JTextField birthdayDT;
    private javax.swing.JTextField birthdayET;
    private javax.swing.JLabel birthdayRL;
    private javax.swing.JLabel birthdayRL1;
    private javax.swing.JLabel birthdayRL2;
    private javax.swing.JTextField birthdayRT;
    private javax.swing.JTextField contactNumberDT;
    private javax.swing.JTextField contactNumberET;
    private javax.swing.JLabel contactNumberRL;
    private javax.swing.JLabel contactNumberRL1;
    private javax.swing.JLabel contactNumberRL2;
    private javax.swing.JTextField contactNumberRT;
    private javax.swing.JButton deleteStudentB;
    private javax.swing.JButton editStudentB;
    private javax.swing.JTextField indexNumberDT;
    private javax.swing.JTextField indexNumberET;
    private javax.swing.JLabel indexNumberRL;
    private javax.swing.JLabel indexNumberRL1;
    private javax.swing.JLabel indexNumberRL2;
    private javax.swing.JTextField indexNumberRT;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField nameDT;
    private javax.swing.JTextField nameET;
    private javax.swing.JLabel nameRL;
    private javax.swing.JLabel nameRL1;
    private javax.swing.JLabel nameRL2;
    private javax.swing.JTextField nameRT;
    private javax.swing.JTextField parentDT;
    private javax.swing.JTextField parentET;
    private javax.swing.JLabel parentRL;
    private javax.swing.JLabel parentRL1;
    private javax.swing.JLabel parentRL2;
    private javax.swing.JTextField parentRT;
    // End of variables declaration//GEN-END:variables
}
