/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tms.views;

import SeverConnector.Connector;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tms.common_classes.PatternChecker;
import tms.controllercommon.StudentController;
import tms.model.Student;

/**
 *
 * @author Nuwantha
 */
public class StudentDetail extends javax.swing.JDialog {

    StudentController studentController;

    /**
     * Creates new form NewJDialog
     */
    public StudentDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            studentController = Connector.getSConnector().getStudentController();
        } catch (SQLException | InterruptedException | ClassNotFoundException | NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        }

        setStudentID();
        loadStudentId();
        addStudentB.setEnabled(false);
        birthdayVali.setVisible(false);
        paprentVali.setVisible(false);
        contactNumberVali.setVisible(false);
        nameVali.setVisible(false);
        birthdayValiE.setVisible(false);
        paprentValiE.setVisible(false);
        contactNumberValiE.setVisible(false);
        nameValiE.setVisible(false);
        
        nameRT.requestFocus();

    }
    public StudentDetail(java.awt.Frame parent, boolean modal,int a){
        this(parent, modal);
        if(a==2){
            jTabbedPane1.setSelectedIndex(1);            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        indexNumberRL = new javax.swing.JLabel();
        nameRL = new javax.swing.JLabel();
        birthdayRL = new javax.swing.JLabel();
        addressRL = new javax.swing.JLabel();
        parentRL = new javax.swing.JLabel();
        contactNumberRL = new javax.swing.JLabel();
        nameRT = new javax.swing.JTextField();
        parentRT = new javax.swing.JTextField();
        contactNumberRT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressRT = new javax.swing.JTextArea();
        addStudentB = new javax.swing.JButton();
        indexNumberRT = new javax.swing.JTextField();
        birthdayVali = new javax.swing.JLabel();
        paprentVali = new javax.swing.JLabel();
        contactNumberVali = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        nameVali = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        indexNumberRL1 = new javax.swing.JLabel();
        nameRL1 = new javax.swing.JLabel();
        birthdayRL1 = new javax.swing.JLabel();
        addressRL1 = new javax.swing.JLabel();
        parentRL1 = new javax.swing.JLabel();
        contactNumberRL1 = new javax.swing.JLabel();
        nameET = new javax.swing.JTextField();
        parentET = new javax.swing.JTextField();
        contactNumberET = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressET = new javax.swing.JTextArea();
        editStudentB = new javax.swing.JButton();
        indexNumberC = new javax.swing.JComboBox<>();
        nameValiE = new javax.swing.JLabel();
        paprentValiE = new javax.swing.JLabel();
        contactNumberValiE = new javax.swing.JLabel();
        dateChooserE = new com.toedter.calendar.JDateChooser();
        birthdayValiE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        indexNumberRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        indexNumberRL.setText("Index Number");

        nameRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        nameRL.setText("Name");

        birthdayRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        birthdayRL.setText("Birthday");

        addressRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        addressRL.setText("Address");

        parentRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        parentRL.setText("Parent");

        contactNumberRL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL.setText("Contact Number");

        nameRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRTActionPerformed(evt);
            }
        });
        nameRT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameRTKeyReleased(evt);
            }
        });

        parentRT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                parentRTKeyReleased(evt);
            }
        });

        contactNumberRT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactNumberRTKeyReleased(evt);
            }
        });

        addressRT.setColumns(20);
        addressRT.setRows(5);
        addressRT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressRTKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(addressRT);

        addStudentB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        addStudentB.setText("Add Student");
        addStudentB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBActionPerformed(evt);
            }
        });
        addStudentB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addStudentBKeyReleased(evt);
            }
        });

        indexNumberRT.setEditable(false);
        indexNumberRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexNumberRTActionPerformed(evt);
            }
        });

        birthdayVali.setBackground(new java.awt.Color(255, 0, 0));
        birthdayVali.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        birthdayVali.setForeground(new java.awt.Color(255, 0, 0));
        birthdayVali.setText("invalid birthday");

        paprentVali.setBackground(new java.awt.Color(255, 0, 0));
        paprentVali.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paprentVali.setForeground(new java.awt.Color(255, 0, 0));
        paprentVali.setText("invalid name");

        contactNumberVali.setBackground(new java.awt.Color(255, 0, 0));
        contactNumberVali.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        contactNumberVali.setForeground(new java.awt.Color(255, 0, 0));
        contactNumberVali.setText("invalid Tele number");

        dateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateChooserKeyReleased(evt);
            }
        });

        nameVali.setBackground(new java.awt.Color(255, 0, 0));
        nameVali.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameVali.setForeground(new java.awt.Color(255, 0, 0));
        nameVali.setText("invalid name");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(indexNumberRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(birthdayRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parentRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactNumberRL, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addStudentB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameRT)
                    .addComponent(parentRT)
                    .addComponent(contactNumberRT)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(indexNumberRT)
                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paprentVali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(contactNumberVali, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(birthdayVali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameVali, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(indexNumberRL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexNumberRT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameRT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameVali, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(birthdayRL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressRL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(birthdayVali, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(parentRT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(parentRL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paprentVali, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactNumberRL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactNumberRT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(contactNumberVali, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(addStudentB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Add Student Detail", jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        indexNumberRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        indexNumberRL1.setText("Index Number");

        nameRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        nameRL1.setText("Name");

        birthdayRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        birthdayRL1.setText("Birthday");

        addressRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        addressRL1.setText("Address");

        parentRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        parentRL1.setText("Parent");

        contactNumberRL1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contactNumberRL1.setText("Contact Number");

        nameET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameETActionPerformed(evt);
            }
        });
        nameET.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameETKeyReleased(evt);
            }
        });

        parentET.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                parentETKeyReleased(evt);
            }
        });

        contactNumberET.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactNumberETKeyReleased(evt);
            }
        });

        addressET.setColumns(20);
        addressET.setRows(5);
        addressET.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressETKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(addressET);

        editStudentB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        editStudentB.setText("Edit Student");
        editStudentB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentBActionPerformed(evt);
            }
        });
        editStudentB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editStudentBKeyReleased(evt);
            }
        });

        indexNumberC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        indexNumberC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                indexNumberCItemStateChanged(evt);
            }
        });

        nameValiE.setBackground(new java.awt.Color(255, 0, 0));
        nameValiE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameValiE.setForeground(new java.awt.Color(255, 0, 0));
        nameValiE.setText("invalid name");

        paprentValiE.setBackground(new java.awt.Color(255, 0, 0));
        paprentValiE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paprentValiE.setForeground(new java.awt.Color(255, 0, 0));
        paprentValiE.setText("invalid name");

        contactNumberValiE.setBackground(new java.awt.Color(255, 0, 0));
        contactNumberValiE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        contactNumberValiE.setForeground(new java.awt.Color(255, 0, 0));
        contactNumberValiE.setText("invalid Tele number");

        dateChooserE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateChooserEKeyReleased(evt);
            }
        });

        birthdayValiE.setBackground(new java.awt.Color(255, 0, 0));
        birthdayValiE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        birthdayValiE.setForeground(new java.awt.Color(255, 0, 0));
        birthdayValiE.setText("invalid birthday");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(indexNumberRL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameRL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(birthdayRL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressRL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parentRL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactNumberRL1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editStudentB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameET)
                    .addComponent(parentET)
                    .addComponent(contactNumberET)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(indexNumberC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooserE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameValiE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paprentValiE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(birthdayValiE, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(contactNumberValiE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(indexNumberRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexNumberC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameET, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(birthdayRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateChooserE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(parentET, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(parentRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(contactNumberRL1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberET, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberValiE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(birthdayValiE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(nameValiE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(paprentValiE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(editStudentB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Edit Student Detail", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Add Student");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indexNumberCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_indexNumberCItemStateChanged
        try {
            String indexNumber = String.valueOf(indexNumberC.getSelectedItem());
            Student searchStudent = studentController.searchStudent(indexNumber);
            nameET.setText(searchStudent.getName());
            parentET.setText(searchStudent.getParentName());
            contactNumberET.setText(searchStudent.getContactNumber());
            String birthday = searchStudent.getBirthDay();
            DateFormat format = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
            Date date = format.parse(birthday);
            dateChooserE.setDate(date);
            addressET.setText(searchStudent.getAddress());

        } catch (RemoteException | SQLException | ClassNotFoundException | ParseException ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_indexNumberCItemStateChanged

    private void editStudentBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentBActionPerformed
        birthdayValiE.setVisible(false);
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date date = dateChooserE.getDate();
        String birthday = df.format(date);
        int birthYear = Integer.parseInt(birthday.substring(0, 4));
        Calendar now = Calendar.getInstance();
        int currentYear = now.get(Calendar.YEAR);
        String studentId = String.valueOf(indexNumberC.getSelectedItem());
        String name = nameET.getText();
        String address = addressET.getText();
        String parent = parentET.getText();
        String contactNumber = contactNumberET.getText();

        if (birthYear >= currentYear - 20 && birthYear <= currentYear - 8) {

            Student student = new Student(studentId, birthday, name, address, parent, contactNumber);
            try {
                boolean editStudentDetail = studentController.editStudentDetail(student);
                if (editStudentDetail) {
                    JOptionPane.showMessageDialog(this, "student detail is updated succesfully");
                    setStudentID();
                } else {
                    JOptionPane.showMessageDialog(this, "student detail is no updated successfully");
                }
            } catch (RemoteException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (!PatternChecker.checkStringdirect(name)) {
            nameValiE.setVisible(true);
            nameET.requestFocus();
           
        } else if (!PatternChecker.checkStringdirect(parent)) {
            paprentValiE.setVisible(true);
            parentET.requestFocus();
           
        } else if (!PatternChecker.checkTelNumdirect(contactNumber)) {
            contactNumberValiE.setVisible(true);
            contactNumberET.requestFocus();
           
        } else {
            birthdayValiE.setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_editStudentBActionPerformed

    private void nameETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameETActionPerformed

    }//GEN-LAST:event_nameETActionPerformed

    private void indexNumberRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexNumberRTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexNumberRTActionPerformed

    private void addStudentBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBActionPerformed
        birthdayVali.setVisible(false);
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date date = dateChooser.getDate();
        String birthday = df.format(date);
        int birthYear = Integer.parseInt(birthday.substring(0, 4));
        Calendar now = Calendar.getInstance();
        int currentYear = now.get(Calendar.YEAR);

        String studentId = indexNumberRT.getText();
        String name = nameRT.getText();
        String address = addressRT.getText();
        String parent = parentRT.getText();
        String contactNumber = contactNumberRT.getText();

        if (!(birthYear >= currentYear - 10 && birthYear <= currentYear - 8)) {
            birthdayVali.setVisible(true);
            dateChooser.requestFocus();
            addStudentB.setEnabled(false);
        } else if (!PatternChecker.checkStringdirect(name)) {
            nameVali.setVisible(true);
            nameRT.requestFocus();
            addStudentB.setEnabled(false);
        } else if (!PatternChecker.checkStringdirect(parent)) {
            paprentVali.setVisible(true);
            parentRT.requestFocus();
            addStudentB.setEnabled(false);
        } else if (!PatternChecker.checkTelNumdirect(contactNumber)) {
            contactNumberVali.setVisible(true);
            contactNumberRT.requestFocus();
            addStudentB.setEnabled(false);
        } else {

            Student student = new Student(studentId, birthday, name, address, parent, contactNumber);
            try {
                boolean addNewStudent = studentController.addNewStudent(student);
                if (addNewStudent) {
                    JOptionPane.showMessageDialog(this, "student are added succesfully");
                    setStudentID();
                    nameRT.setText("");
                    addressRT.setText("");
                    parentRT.setText("");
                    contactNumberRT.setText("");
                    loadStudentId();
                } else {
                    JOptionPane.showMessageDialog(this, "student are not added successfully");
                }
            } catch (RemoteException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_addStudentBActionPerformed

    private void nameRTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameRTKeyReleased

        nameVali.setVisible(false);
        String newtext = PatternChecker.checkstring(nameRT.getText());
        nameRT.setText(newtext);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (PatternChecker.checkStringdirect(nameRT.getText())) {
                dateChooser.requestFocus();
            } else {
                birthdayVali.setVisible(true);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            dateChooser.requestFocus();
        }
        EnableAddButton();
    }//GEN-LAST:event_nameRTKeyReleased

    private void nameRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRTActionPerformed

    private void dateChooserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateChooserKeyReleased
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                addressRT.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                addressRT.requestFocus();
                break;
            case KeyEvent.VK_UP:
                nameRT.requestFocus();
                break;
            default:
                break;
        }
        EnableAddButton();
    }//GEN-LAST:event_dateChooserKeyReleased

    private void addressRTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressRTKeyReleased
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                parentRT.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                parentRT.requestFocus();
                break;
            case KeyEvent.VK_UP:
                dateChooser.requestFocus();
                break;
            default:
                break;
        }
        EnableAddButton();

        // TODO add your handling code here:
    }//GEN-LAST:event_addressRTKeyReleased

    private void parentRTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parentRTKeyReleased
        paprentVali.setVisible(false);
        String newtext = PatternChecker.checkstring(parentRT.getText());
        parentRT.setText(newtext);
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (PatternChecker.checkStringdirect(parentRT.getText())) {
                    contactNumberRT.requestFocus();
                } else {
                    paprentVali.setVisible(true);
                }
                break;
            case KeyEvent.VK_DOWN:
                contactNumberRT.requestFocus();
                break;
            case KeyEvent.VK_UP:
                addressRT.requestFocus();
                break;
            default:
                break;
        }
        EnableAddButton();

        // TODO add your handling code here:
    }//GEN-LAST:event_parentRTKeyReleased

    private void contactNumberRTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumberRTKeyReleased
        contactNumberVali.setVisible(false);
        String newtext = PatternChecker.checkTelNum(contactNumberRT.getText());
        contactNumberRT.setText(newtext);
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (PatternChecker.checkTelNumdirect(contactNumberRT.getText())) {

                    addStudentB.requestFocus();
                } else {
                    contactNumberVali.setVisible(true);
                }
                break;
            case KeyEvent.VK_DOWN:
                addStudentB.requestFocus();
                break;
            case KeyEvent.VK_UP:
                parentRT.requestFocus();
                break;
            default:
                break;
        }
        EnableAddButton();

    }//GEN-LAST:event_contactNumberRTKeyReleased

    private void nameETKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameETKeyReleased
        nameValiE.setVisible(false);
        String newtext = PatternChecker.checkstring(nameET.getText());
        nameET.setText(newtext);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (PatternChecker.checkStringdirect(nameET.getText())) {
                dateChooserE.requestFocus();
            } else {
                nameValiE.setVisible(true);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            dateChooserE.requestFocus();
        }


    }//GEN-LAST:event_nameETKeyReleased

    private void dateChooserEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateChooserEKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addressET.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserEKeyReleased

    private void addressETKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressETKeyReleased
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                parentET.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                parentET.requestFocus();
                break;
            case KeyEvent.VK_UP:
                dateChooserE.requestFocus();
                break;
            default:
                break;
        }

    }//GEN-LAST:event_addressETKeyReleased

    private void parentETKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parentETKeyReleased
        paprentValiE.setVisible(false);
        String newtext = PatternChecker.checkstring(parentET.getText());
        parentET.setText(newtext);
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (PatternChecker.checkStringdirect(parentET.getText())) {
                    contactNumberET.requestFocus();
                } else {
                    paprentValiE.setVisible(true);
                }
                break;
            case KeyEvent.VK_DOWN:
                contactNumberET.requestFocus();
                break;
            case KeyEvent.VK_UP:
                addressET.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_parentETKeyReleased

    private void contactNumberETKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumberETKeyReleased
        contactNumberValiE.setVisible(false);
        String newtext = PatternChecker.checkTelNum(contactNumberET.getText());
        contactNumberET.setText(newtext);
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (PatternChecker.checkTelNumdirect(contactNumberET.getText())) {
                    editStudentB.requestFocus();
                } else {
                    contactNumberValiE.setVisible(true);
                }
                break;
            case KeyEvent.VK_DOWN:
                editStudentB.requestFocus();
                break;
            case KeyEvent.VK_UP:
                parentET.requestFocus();
                break;
            default:
                break;
        }


    }//GEN-LAST:event_contactNumberETKeyReleased

    private void addStudentBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addStudentBKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            contactNumberRT.requestFocus();
        }
    }//GEN-LAST:event_addStudentBKeyReleased

    private void editStudentBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editStudentBKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            contactNumberET.requestFocus();
        }

    }//GEN-LAST:event_editStudentBKeyReleased

    private void setStudentID() {
        try {
            Student lastAddedStudent = studentController.getLastAddedStudent();
            String studentId = lastAddedStudent.getStudentId();
            int count = Integer.parseInt(studentId.substring(2));
            int studentCount = count + 1;
            if (studentCount < 10) {
                indexNumberRT.setText("St000" + String.valueOf(studentCount));
            } else if (studentCount < 100) {
                indexNumberRT.setText("St00" + String.valueOf(studentCount));
            } else if (studentCount < 1000) {
                indexNumberRT.setText("St0" + String.valueOf(studentCount));
            } else {
                indexNumberRT.setText("St" + String.valueOf(studentCount));
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadStudentId() {
        indexNumberC.removeAllItems();
        try {
            ArrayList<Student> allStudent = studentController.getAllStudent();
            for (Student student : allStudent) {
                indexNumberC.addItem(student.getStudentId());
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void EnableAddButton() {
        if (nameRT.getText().trim().length() != 0 && addressRT.getText().trim().length() != 0 && parentRT.getText().trim().length() != 0 && contactNumberRT.getText().trim().length() != 0) {
            addStudentB.setEnabled(true);
        } else {
            addStudentB.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentDetail dialog = new StudentDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentB;
    private javax.swing.JTextArea addressET;
    private javax.swing.JLabel addressRL;
    private javax.swing.JLabel addressRL1;
    private javax.swing.JTextArea addressRT;
    private javax.swing.JLabel birthdayRL;
    private javax.swing.JLabel birthdayRL1;
    private javax.swing.JLabel birthdayVali;
    private javax.swing.JLabel birthdayValiE;
    private javax.swing.JTextField contactNumberET;
    private javax.swing.JLabel contactNumberRL;
    private javax.swing.JLabel contactNumberRL1;
    private javax.swing.JTextField contactNumberRT;
    private javax.swing.JLabel contactNumberVali;
    private javax.swing.JLabel contactNumberValiE;
    private com.toedter.calendar.JDateChooser dateChooser;
    private com.toedter.calendar.JDateChooser dateChooserE;
    private javax.swing.JButton editStudentB;
    private javax.swing.JComboBox<String> indexNumberC;
    private javax.swing.JLabel indexNumberRL;
    private javax.swing.JLabel indexNumberRL1;
    private javax.swing.JTextField indexNumberRT;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameET;
    private javax.swing.JLabel nameRL;
    private javax.swing.JLabel nameRL1;
    private javax.swing.JTextField nameRT;
    private javax.swing.JLabel nameVali;
    private javax.swing.JLabel nameValiE;
    private javax.swing.JLabel paprentVali;
    private javax.swing.JLabel paprentValiE;
    private javax.swing.JTextField parentET;
    private javax.swing.JLabel parentRL;
    private javax.swing.JLabel parentRL1;
    private javax.swing.JTextField parentRT;
    // End of variables declaration//GEN-END:variables
}
